services:
  backend:
    build:
      context: ./backend
      target: build
    command: ["dotnet", "watch", "--project", "OidcServer"]
    volumes:
      - ./backend/OidcServer/Src:/app/OidcServer/Src
      - ./Properties:/app/Properties
    environment:
      AdminCredentials__Username: adminuser
      AdminCredentials__Password: adminpass
      Jwt__Issuer: oidc-server
      Jwt__Audience: oidc-frontend
      Jwt__ExpirationMinutes: 360
      Jwt__SigningKey: superhardkeyDadasuperhardkeyDada
    ports:
      - 8080:8080
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 4200:4200
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 9000:80